{
    "tag": "alice",
    "time": 0,
    "origin": {
        "col": 0,
        "row": 0
    },
    "length": 4,
    "width": 4,
    "cells": [
        {
            "value": {
                "ty": "int",
                "data": [
                    1
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    1
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    2
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    2
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    3
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    3
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "none",
                "data": null
            },
            "definition": {
                "ty": "count",
                "data": [
                    0,
                    0,
                    4,
                    1,
                    1
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    1
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    1
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    2
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    2
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    3
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    3
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "none",
                "data": null
            },
            "definition": {
                "ty": "count",
                "data": [
                    0,
                    1,
                    4,
                    1,
                    2
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    1
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    1
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    2
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    2
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    3
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    3
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "none",
                "data": null
            },
            "definition": {
                "ty": "count",
                "data": [
                    0,
                    2,
                    4,
                    1,
                    3
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    1
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    1
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    2
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    2
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "int",
                "data": [
                    3
                ]
            },
            "definition": {
                "ty": "int",
                "data": [
                    3
                ],
                "promises": null
            }
        },
        {
            "value": {
                "ty": "none",
                "data": null
            },
            "definition": {
                "ty": "count",
                "data": [
                    0,
                    3,
                    4,
                    1,
                    4
                ],
                "promises": null
            }
        }
    ]
}